### ISSUE TITLE
Camera Z-axis rotation doesnt work with Cinemachine asset

### ISSUE THREAD

**Issue by FlowingSPDG** [advancedfx/afx-unity-interop#3]
Cinemachine's Virtual camera Z-axis doesnt apply rotation value to override camera,
X and Y is working correctly
https://www.youtube.com/watch?v=yg39KpfS5qc&feature=youtu.be

**Comment by dtugend** [comment]
It works fine for me:
![works](https://user-images.githubusercontent.com/3610128/66343511-132ccc00-e94c-11e9-8067-87dbf6e3d3b3.jpg)

Things to check for:
- The override camera must be active every frame, only enabling it sporadically won't work, because the game will set it back (un-rotate) in next frame. What this means setting camera and expecting it to getting the same value from the game won't work. You need to drive it from the Unity end.
- Maybe you are using mirv_cals on the csgo end, be sure to check that they are not active (try with a clean config).
